server:
  port: 9080


spring:
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/cms
     username: postgres
     password: root


     thymeleaf:
       mode: HTML5
       encoding: UTF-8
       content-type: text/html
       cache: false

     aop: 
       auto: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ritu.cms.pojo